### ISSUE TITLE
Not supported on latest R update

### ISSUE THREAD

**Issue by ghost** [juliasilge/silgelib#2]
I've just updated R Studio and R and silgelib is not supported. Can't knit to markdown and not sure what is requiring silgelib in my code. 

R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.2.1

**Comment by juliasilge** [comment]
This package is only on GitHub, not on CRAN, so you'll need to install via `devtools::install_github("juliasilge/silgelib")`. Good luck!
